"""
Candidate Profile JSON (Data Layer) - Component #10 for CONDUCTOR.
"""
from candidate_profile.models import (
    ApplicationPreferences,
    CandidateProfile,
    ContactInfo,
    EducationRecord,
    ExperienceRecord,
    HistoryRef,
    Identity,
    ProficiencyLevel,
    ProfileMetadata,
    SkillRecord,
    SourceProvenance,
)
from candidate_profile.storage import (
    CandidateProfileStore,
    PersistenceError,
    get,
    list_versions,
    put,
)
from candidate_profile.migrations import (
    CURRENT_SCHEMA_VERSION,
    MigrationError,
    MigrationRegistry,
    UnmigratableSchemaVersionError,
    default_migration_registry,
    migrate_profile,
)
from candidate_profile.projections import (
    ApplicationView,
    CertificationEntry,
    ContactProfile,
    EducationEntry,
    ExperienceEntry,
    GleanerQuery,
    OutreachContext,
    ProjectEntry,
    ResearchScope,
    ResumeProfile,
    SearchCriteria,
    UsherCandidateProfile,
    to_application_view,
    to_gleaner_query,
    to_outreach_context,
    to_research_scope,
    to_resume_profile,
    to_search_criteria,
    to_usher_profile,
)
from candidate_profile.concurrency import (
    ALL_SECTIONS,
    APPEND_ONLY_SECTIONS,
    OWNERSHIP_MAP,
    CandidateProfilePatch,
    OwnershipViolationError,
    merge_candidate_profile,
    normalize_component_name,
)
from candidate_profile.observability import (
    CANDIDATE_PROFILE_OWNERSHIP_VIOLATIONS_TOTAL,
    CANDIDATE_PROFILE_SCHEMA_VERSION_GAUGE,
    CANDIDATE_PROFILE_VALIDATION_FAILURES_TOTAL,
    CANDIDATE_PROFILE_WRITE_LATENCY_SECONDS,
    CANDIDATE_PROFILE_WRITES_TOTAL,
    check_schema_version_drift,
    compute_taxonomy_coverage,
    record_ownership_violation,
    record_profile_write,
    record_schema_version,
    record_validation_failure,
)

__all__ = [
    # Canonical Models
    "ApplicationPreferences",
    "CandidateProfile",
    "CandidateProfileStore",
    "ContactInfo",
    "EducationRecord",
    "ExperienceRecord",
    "HistoryRef",
    "Identity",
    "ProficiencyLevel",
    "ProfileMetadata",
    "SkillRecord",
    "SourceProvenance",
    # Storage & Migrations
    "PersistenceError",
    "MigrationError",
    "UnmigratableSchemaVersionError",
    "CURRENT_SCHEMA_VERSION",
    "MigrationRegistry",
    "default_migration_registry",
    "get",
    "put",
    "list_versions",
    "migrate_profile",
    # Projections & Adapters
    "ResumeProfile",
    "ContactProfile",
    "ExperienceEntry",
    "ProjectEntry",
    "EducationEntry",
    "CertificationEntry",
    "to_resume_profile",
    "GleanerQuery",
    "SearchCriteria",
    "to_gleaner_query",
    "to_search_criteria",
    "OutreachContext",
    "to_outreach_context",
    "ApplicationView",
    "to_application_view",
    "UsherCandidateProfile",
    "to_usher_profile",
    "ResearchScope",
    "to_research_scope",
    # Concurrency & Reducer
    "CandidateProfilePatch",
    "OwnershipViolationError",
    "OWNERSHIP_MAP",
    "APPEND_ONLY_SECTIONS",
    "ALL_SECTIONS",
    "merge_candidate_profile",
    "normalize_component_name",
    # Observability & Metrics
    "CANDIDATE_PROFILE_WRITES_TOTAL",
    "CANDIDATE_PROFILE_VALIDATION_FAILURES_TOTAL",
    "CANDIDATE_PROFILE_SCHEMA_VERSION_GAUGE",
    "CANDIDATE_PROFILE_WRITE_LATENCY_SECONDS",
    "CANDIDATE_PROFILE_OWNERSHIP_VIOLATIONS_TOTAL",
    "record_profile_write",
    "record_validation_failure",
    "record_ownership_violation",
    "record_schema_version",
    "check_schema_version_drift",
    "compute_taxonomy_coverage",
]
